-- MySQL Script generated by MySQL Workbench
-- Thu Apr  2 10:44:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SaltDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SaltDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SaltDB` DEFAULT CHARACTER SET utf8 ;
USE `SaltDB` ;

-- -----------------------------------------------------
-- Table `SaltDB`.`Salt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SaltDB`.`Salt` (
  `Id` VARCHAR(45) NOT NULL,
  `Salt` BINARY(45) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
